/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as DailyIndexRouteImport } from './routes/daily.index'
import { Route as DailyDateRouteImport } from './routes/daily.$date'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyIndexRoute = DailyIndexRouteImport.update({
  id: '/daily/',
  path: '/daily/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyDateRoute = DailyDateRouteImport.update({
  id: '/daily/$date',
  path: '/daily/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/leaderboard': typeof LeaderboardRoute
  '/sign-in': typeof SignInRoute
  '/submit': typeof SubmitRoute
  '/daily/$date': typeof DailyDateRoute
  '/daily/': typeof DailyIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/leaderboard': typeof LeaderboardRoute
  '/sign-in': typeof SignInRoute
  '/submit': typeof SubmitRoute
  '/daily/$date': typeof DailyDateRoute
  '/daily': typeof DailyIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/leaderboard': typeof LeaderboardRoute
  '/sign-in': typeof SignInRoute
  '/submit': typeof SubmitRoute
  '/daily/$date': typeof DailyDateRoute
  '/daily/': typeof DailyIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/leaderboard'
    | '/sign-in'
    | '/submit'
    | '/daily/$date'
    | '/daily/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/leaderboard'
    | '/sign-in'
    | '/submit'
    | '/daily/$date'
    | '/daily'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/leaderboard'
    | '/sign-in'
    | '/submit'
    | '/daily/$date'
    | '/daily/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LeaderboardRoute: typeof LeaderboardRoute
  SignInRoute: typeof SignInRoute
  SubmitRoute: typeof SubmitRoute
  DailyDateRoute: typeof DailyDateRoute
  DailyIndexRoute: typeof DailyIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily/': {
      id: '/daily/'
      path: '/daily'
      fullPath: '/daily/'
      preLoaderRoute: typeof DailyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily/$date': {
      id: '/daily/$date'
      path: '/daily/$date'
      fullPath: '/daily/$date'
      preLoaderRoute: typeof DailyDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LeaderboardRoute: LeaderboardRoute,
  SignInRoute: SignInRoute,
  SubmitRoute: SubmitRoute,
  DailyDateRoute: DailyDateRoute,
  DailyIndexRoute: DailyIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
